### ISSUE TITLE
Reuse parts of AuthenticRoast

### ISSUE THREAD

**Issue by ratcashdev** [omnifaces/omnisecurity#1]
Code: https://code.google.com/p/authenticroast/
Tutorial: http://www.ibm.com/developerworks/library/j-authenticroast/

It's already unmaintained, however, there's already lots of code that works, and the idea is pretty much the same. Reason why I am suggesting this is because I am already using AuthenticRoast for a new project, but I am wondering if it would be reasonable to move to omnisecurity, especially when the next provider to be implemented (for me) is OAuth2.

**Comment by arjantijms** [comment]
I remember seeing this one before, thanks for letting me remember it.

Indeed, there are similar goals here. At the moment OmniSecurity is mostly an experimental project, where I experiment with different designs and approaches. I perhaps have to make it more clear on the homepage, but it's not really intended for people to just take and use in their applications.

As I'm on the Java EE security EG, I hope to feed back some of the results from this experimental code back into Java EE itself.

**Comment by ratcashdev** [comment]
And just when I said OAuth2, i came accross this: http://tav.espians.com/oauth-3.0-the-sane-and-simple-way-to-do-it.html
and this: https://github.com/OAuth3
