### ISSUE TITLE
Link to SPECs broken

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [omnifaces/omnisecurity#5]
JAVAEE_SPEC-9 and JASPIC_SPEC-17 in http://omnisecurity.omnifaces.org/

**Comment by arjantijms** [comment]
Thanks for the notification, the assumption was that Oracle will put redirects in place at some point for these links, but in this case it's perhaps easier to update them manually. Thx!

**Comment by arjantijms** [comment]
Links updated, thanks again!
